### PR TITLE
refactor: migrate off modal paragon deprecated component

### PR DESCRIPTION
**Pull request by Mashal-m**
### Ticket
[Migrate off deprecated Paragon components](https://github.com/openedx/frontend-wg/issues/102)

### What has changed?

- Migrate off paragon modal deprecation in **WarningModal.jsx**

### CODE REVIEW

**Comment by arbrandes** [comment]
@leangseu-edx, any chance you could review this?

@Mashal-m,  mind updating the branch with master in the meantime?

**Review by leangseu-edx — CHANGES_REQUESTED** [review]
Shouldn't `ModalDialog.body` is uppercase? 
Anyway, can you use `ModalDialogBody`, ModalDialogHeader`.... syntax instead? Since those are import directly and it is less likely to create typo and it is easier to check with the doc on paragon https://paragon-openedx.netlify.app/components/modal/modal-dialog/

**Comment by Mashal-m** [comment]
> Shouldn't `ModalDialog.body` is uppercase? Anyway, can you use `ModalDialogBody`, ModalDialogHeader`.... syntax instead? Since those are import directly and it is less likely to create typo and it is easier to check with the doc on paragon https://paragon-openedx.netlify.app/components/modal/modal-dialog/

According to paragon documentation, we can only import _ModaDialog_ and _ModalCloseButton_ directly. It is mandatory to use header, title, etc like this _ModalDialog.Body_.

**Review by leangseu-edx — APPROVED** [review]
LGTM 👍

**Comment by leangseu-edx** [comment]
> According to paragon documentation, we can only import _ModaDialog_ and _ModalCloseButton_ directly. It is mandatory to use header, title, etc like this _ModalDialog.Body_.

Fair. It seems all of the example are doing that.

**Pull request merged**
