### PR TITLE
fix: pass sequenceId to api call

### PR DESCRIPTION
**Pull request by ilee2u**
Fix for https://2u-internal.atlassian.net/browse/COSMO-125

We seemed to forget to pass the sequenceId to the backend API call in thunks.js. I just added that back in, hopefully this should work on stage now.

### CODE REVIEW

**Comment by Zacharis278** [comment]
this does just seem like a missed piece of code. One question tho, does this work correctly if the user is outside of the exam section? Like on the course outline or viewing a different piece of course content?

**Review by alangsto — APPROVED** [review]

**Comment by ilee2u** [comment]
> this does just seem like a missed piece of code. One question tho, does this work correctly if the user is outside of the exam section? Like on the course outline or viewing a different piece of course content?

I tried messing around with this on stage, going between the course view and the exam sequence view, which actually didn't cause any problems. In fact, I only saw the error in the exam sequence view, and interestingly, going between both views caused the problem not to happen.

Also, I determined that this was probably happening because of pollExamAttempt due to it always happening when the timer hit the :00 minute mark, meaning that this was going off every 60 seconds when pollAttempt is called.

**Comment by Zacharis278** [comment]
@rijuma this might have been the cause of your bug as well.

@ilee2u have we tested those cases with this fix added? Wanna make sure the state we're pulling has the correct content id for the active attempt if this happens to get called when not in the right sequence.

**Review by schenedx — APPROVED** [review]
👍

**Comment by Zacharis278** [comment]
@ilee2u did we ever confirm this works when the user is outside of the particular exam section? I just tried a timed exam on stage and I get an error when viewing the outline with the timer running.

**Pull request merged**
